name: "Static Site: Deploy"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd site
      - run: npm ci
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSHKEY }}
          script: |
            cd rafraser
            git pull
            npm install
            npm run all
